### ISSUE TITLE
BUG: Starting a timer in the pinned section will not save the running timer

### ISSUE THREAD

**Issue by agvendiola** [rsalayo/OpeniT.Timesheet.Issues#26]
Browser: Chrome
Scenario
1. I have a running task, say taskA
2. I started another pinned task called taskB
3. The timesheet will start taskB and end taskA but with Hours=0
3.1. expectation is to end the time of TaskA and record it
4. later found out that there's actually an entry when I refresh the page

![timesheet](https://cloud.githubusercontent.com/assets/28588930/26545678/1b917882-4499-11e7-8280-d91ec0324d0f.gif)

**Comment by rsalayo** [comment]
Due to the my attempt to reduce the number of API calls per action, I tried to clear the timer to any task for simplicity. And to prevent tampering of the data, the timer on the client is cosmetics only. The real timer is computed in the server, that is why it show's up when you refresh the page. I'll fix it now but changes will be available on next build. Thanks!
