### ISSUE TITLE
Resetting ticket edit fields when changing day?

### ISSUE THREAD

**Issue by cyborgar** [rsalayo/OpeniT.Timesheet.Issues#43]
I noticed that the current entires for a ticket is kept when moving between days. Is this by design or just "accident"?

If not by design clearing these may be an idea, though I have to note that this was not a problem for me when updating hours since I used the templates a lot (which set all fields at "select").

**Comment by rsalayo** [comment]
It is by design, it is used for copying and moving task from one date to another. Since the table doesn't have a means of editing dates (if a user entered task into a wrong date, he can edit it and change the date instead of deleting the wrong entry and creating a new one in the correct date). This is one of the reason why I haven't started on #16

**Comment by cyborgar** [comment]
Ah, I used the following procedure to move entry added on wrong date

1. Pin entry
2. Delete entry on current date
3. Use template on wanted date
4. Delete template

Note that I tested your method and that is more efficient in the sense that you need fewer operations. However, I have to admit that I would never have guess that it worked this way. I.e. it's not really intuitive that changing the data on the top actually moves an existing issue. I figured out this out after repeated "Uh, something is wrong" errors. I tried to basically use the same procedure as over.

1. "load" by pressing edit entry
2. delete existing entry
3. move to correct date
4. save (remebered) task

which doesn't work.

Note the visual parts of the editor does not really tell you that you are now currently moving existing entry. I think that is a good idea. 

BTW, why is #16 a problem when you are sort of already doing inline editing of date?

**Comment by rsalayo** [comment]
With #16, you won't be able to move data from one date to another as changing the date will reload the table. While putting it on the data input (left side will preserve it while context has changed).

You're getting the "Urgh, something is wrong" since the data you're trying to edit doesn't exist anymore when you deleted it.

Let's put it this way. You can use **Copy** as a template while **Edit** will really edit that entry (including changing dates).

**Comment by cyborgar** [comment]
I do not have a problem with the functionality now that I understand how it works. It's just not clear (at least it wasn't to me) that this was going to happen.

I.e. we should possibly see if we can find a way to visually show what you are doing. I.e. I would give the current entry a color when pressing "edit" and also use this as the background in the "entry block" on the left. That way these two items are sort of locked together. This is sort of what I say in #44.

**Comment by cyborgar** [comment]
Actually since the "date" is also part of what could be edited this should also be marked the same way.

**Comment by rsalayo** [comment]
Will do... just finishing other stuffs. Will let you know when #44 has been improved.

**Comment by rsalayo** [comment]
Btw, I usually push updates during the weekend to avoid interrupting other offices up-time (Plus I need to test it in staging first aside from the regular unit testing as I push updates in bulk).
