### ISSUE TITLE
(Enhancement) Hours per day

### ISSUE THREAD

**Issue by vbitara** [rsalayo/OpeniT.Timesheet.Issues#47]
I think the hours per day is calculated by **Total Required time (192hrs) * Number of days** which results to a constant value. As an example, 8.73 per for the month of June.

I would like to suggest if we can make the computation for the hours per day like this:
**Total Time Remaining / Remaining days**

As an example, I have spent 97.41 hours on the month of June, based on the screenshot.

Time Remaining:  **94.59** (192-97.41)
Remaining days: 13 days

Hours/Day: 7.28 hours / day

![image](https://user-images.githubusercontent.com/28781641/27126506-48cbc76a-512a-11e7-83c1-3cb68775b9dc.png)

I hope you can consider this.
Thank you!

**Comment by rsalayo** [comment]
Try to get it approved by your LM and other POs (@agvendiola @lisleta) for other teams.
AFAIK, we are still required to come to the office regardless if you already reached your working hours for the month unless you use it as Time-Off.

With your proposal, if an employee worked for 12hours for the first few days of the month. The system will suggest that he/she doesn't need to work for the rest of the month as he/she already completed the required hours for the month.

The purpose of the suggested hours is to practice a healthy working environment and avoid overworking/underworking.

**Comment by agvendiola** [comment]
I actually like the request because it helps in managing time.  My view is under the assumption that employees are honest and work hard at the time he is most needed and relaxes a bit when not.

I believe that I don't share most of our LMs and POs opinion so I'm sure it will not get approved.  It goes against the norm

**Comment by lisleta** [comment]
I like this request too, although I understand your point that the employee may misinterpret that s/he doesn't need to work once the required hours are completed.

**Comment by rsalayo** [comment]
@vbitara, this is harder than I thought since some employees have different contracts so just counting the number of working days is not enough.

For now I added a Easter Egg for this that when you click the lightning icon, it toggles/gives the suggested hours for the current day.
![image](https://user-images.githubusercontent.com/1053166/27549852-1098b05a-5a63-11e7-9dfb-3387718419bb.png)
