### ISSUE TITLE
Edit Record doesn't show the hours on the side panel

### ISSUE THREAD

**Issue by bryanjulius** [rsalayo/OpeniT.Timesheet.Issues#54]
I encountered this when I tried to edit the task from previous day. The hours is not shown, I guess its natural to see the hours you recorded on the edit panel

Update: This seem to occur only when the Active Timer is running.

**Comment by rsalayo** [comment]
You mean you are trying to edit a task from previous day that has a timer running?

If so, since the hour is not yet saved on the server and to prevent messing the timer. You'll have to stop the timer first before you can edit.

But if the timer is not on the task that you're editing. Then this is a bug but I can't reproduce it. Please provide steps to reproduce. thanks.

**Comment by bryanjulius** [comment]
Hi Romeo,
Yes the timer is on the task that I am editing, so this is not an issue. The problem I guess is that I did not saw the red button for the active timer indication on the task itself. I will try to do the same scenario before I leave the office and comment back on this.

**Comment by rsalayo** [comment]
There's another **Stop** button on the upper right. That will stop any active timer (current/previous day).

**Comment by bryanjulius** [comment]
Verified that the active timer button was not shown on the task itself even if its still active. But yes I can just use the Stop button on the upper right.
